Updated package.json
RisingStack/graffiti-mongoose pull request #205
Opened 2017-01-26 20:56 UTC by dangreenisrael

Couldn’t get graphql up to 0.9.0, seems there was a breaking change

2017-01-26 21:19 UTC, tothandras requested changes

2017-01-26 21:19 UTC, tothandras commented on .gitignore
> +.idea
this should be put in your global `gitignore`, mine looks like this:
```
$ cat ~/.gitignore_global
```
```
.sync-config.cson
*~
.DS_Store
.idea
.vscode
npm-debug.log
.DS_Store
.history
```

2017-01-26 21:28 UTC, dangreenisrael commented
Removed.

2017-01-26 21:30 UTC, dangreenisrael commented
Perhaps the breaking changes didn't kick in until the minor version update

2017-01-27 12:18 UTC, tothandras commented
included by #206

2017-01-27 12:18 UTC, closed without merging